### ISSUE TITLE
line 1919: [-1]: bad array subscript

### ISSUE THREAD

**Issue by karhukuoma** [jvehent/cipherscan#101]
On x64 CentOS Linux release 7.1.1503 (Core) I get the error
./cipherscan: line 1919: [-1]: bad array subscript

bash -version
GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)

**Comment by tomato42** [comment]
what parameters do you use? How do you run it exactly?

**Comment by karhukuoma** [comment]
./cipherscan google.com
that was my command line

**Comment by tomato42** [comment]
could you change the code there to look like this:
```
echo "parameters; $*"
PARAMS=("$@")
echo "PARAMS: ${PARAMS[*]}"
TARGET=${PARAMS[-1]}
unset PARAMS[-1]
```

and then provide output?

**Comment by karhukuoma** [comment]
here's a excerpt from cipherscan with line numbers:
```
1916 echo "parameters; $*"
1917 PARAMS=("$@")
1918 echo "PARAMS: ${PARAMS[*]}"
1919 TARGET=${PARAMS[-1]}
1920 unset PARAMS[-1]
```
and my command output
```
./cipherscan google.com
parameters; google.com
PARAMS: google.com
./cipherscan: line 1920: [-1]: bad array subscript
```

**Comment by tomato42** [comment]
that doesn't make sense, it's like your version of bash doesn't support referring to the last element of array directly...

https://www.gnu.org/software/bash/manual/bashref.html#Arrays says though 
```
When assigning to an indexed array, if name is subscripted by a negative number, that
number is interpreted as relative to one greater than the maximum index of name, so
negative indices count back from the end of the array, and an index of -1 references the
last element. 
```
and 
```
The unset builtin is used to destroy arrays. unset name[subscript] destroys the array
element at index subscript. Negative subscripts to indexed arrays are interpreted as
described above.
```
so I don't know what's happening

could you try running in your bash shell the following:
```
arr=("first" "second" "third")
echo ${arr[-1]}
unset arr[-1]
echo ${arr[-1]}
```

and maybe try running the command as `bash ./cipherscan google.com`

**Comment by karhukuoma** [comment]
```
[user@hostname cipherscan-master]$ arr=("first" "second" "third")
[user@hostname cipherscan-master]$ echo ${arr[-1]}
third
[user@hostname cipherscan-master]$ unset arr[-1]
bash: [-1]: bad array subscript
[user@hostname cipherscan-master]$ echo ${arr[-1]}
third
```

**Comment by tomato42** [comment]
then that's a bug in your version of bash

**Comment by jvehent** [comment]
Oh boy... did someone in the QA department of Red Hat missed something? :p

**Comment by floatingatoll** [comment]
Could you please include here the output of ```env | grep BASH_```?

**Comment by tomato42** [comment]
...maybe... :sweat_smile:

I need to test that on actual RHEL

**Comment by floatingatoll** [comment]
Bash Changelog:

```
This document details the changes between this version, bash-4.3-alpha,
and the previous version, bash-4.2-release.

3.  New Features in Bash

x.  The shell now allows assigning, referencing, and unsetting elements of
    indexed arrays using negative subscripts (a[-1]=2, echo ${a[-1]}) which
    count back from the last element of the array.
```

**Comment by floatingatoll** [comment]
So, I assume we aren't requiring bash 4.3, and so this needs to be altered not to use negative subscripts.

**Comment by tomato42** [comment]
yeah. it does seem to be a new feature in bash, so we should workaround it

**Comment by karhukuoma** [comment]
I can verify that that commit which @floatingatoll committed, is working on the CentOS 7 bash version discussed in this issue. Thank you everyone and thanks for the great tool.
