### ISSUE TITLE
analyze.py usage example isn't correct

### ISSUE THREAD

**Issue by edmorley** [jvehent/cipherscan#115]
**STR:**
1) ./analyze.py --help
2) Run the example `./analyze.py mozilla.org`

**Expected:**
The example (or another domain substituted in) works.

**Actual:**
```
$ ./analyze.py mozilla.org
usage:
* Analyze a single target, invokes cipherscan: $ ./analyze.py -t [target]
* Evaluate json results passed through stdin:  $ python analyze.py < target_results.json
example: ./analyze.py mozilla.org
analyze.py: error: argument infile: can't open 'mozilla.org': [Errno 2] No such file or directory: 'mozilla.org'
```

I was going to just fix the usage example here:
https://github.com/jvehent/cipherscan/blob/18b0d1b952d027d20e38f07329817873ec077d26/analyze.py#L456

...however ideally the `-t` parameter would not be necessary, and the example as phrased would just work. Perhaps if the item passed as the first parameter doesn't exist as a file, analyze.py could prompt "Results file does not exist, is this a domain you wish to scan? [Yn]".

**Comment by jvehent** [comment]
I updated the example to show `-t`. Maybe in the future we can rewrite the argparser to not require it.

**Comment by edmorley** [comment]
Thank you :-)
