### ISSUE TITLE
ubuntu 14 docker image run error

### ISSUE THREAD

**Issue by centminmod** [jvehent/cipherscan#52]
Hi I am trying to run cipherscan from a ubuntu docker image and get the following error ?

    ./cipherscan www.google.com:443
    ...................
    Target: www.google.com:443
    
    ./cipherscan: line 512: column: command not found
    
    Certificate: trusted, 2048 bit, sha1WithRSAEncryption signature
    TLS ticket lifetime hint: 100800
    OCSP stapling: not supported
    Server side cipher ordering

**Comment by tomato42** [comment]
you need to have `util-linux` installed for the text output, JSON output should work without `column` utility present

**Comment by centminmod** [comment]
thanks @tomato42 seems I already had util-linux and still get that above error ?

    apt-cache policy util-linux
    util-linux:
      Installed: 2.20.1-5.1ubuntu20.4
      Candidate: 2.20.1-5.1ubuntu20.4
      Version table:
     *** 2.20.1-5.1ubuntu20.4 0
            500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
            100 /var/lib/dpkg/status
         2.20.1-5.1ubuntu20 0
            500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

**Comment by tomato42** [comment]
hmm, that's weird, both on Arch and Fedora `column` is in `linux-util`...

Could you see what package according to apt should have it?
```
apt-file update
apt-file find column
```
should do it

Alternatively, the [ubuntu packages](http://packages.ubuntu.com/search?searchon=contents&keywords=column&mode=exactfilename&suite=trusty&arch=any) says it should be in `bsdmainutils` (?!)

**Comment by centminmod** [comment]
thanks @tomato42 it was bsdmainutils package that fixed it :)
