### ISSUE TITLE
Exporting to JSON with the -j command line option

### ISSUE THREAD

**Issue by RoldanLT** [jvehent/cipherscan#55]
Running the script on Ubuntu 15.04 64 Bit
I got this error.

$ ./cipherscan --curves -j www.phcorner.net | j
j: command not found

**Comment by jvehent** [comment]
`|j` is a custom alias that I set to `python -mjson.tool` in my bashrc. You don't need it, just remove it.

**Comment by RoldanLT** [comment]
Thanks, works fine now but result is cluttered :|
![image](https://cloud.githubusercontent.com/assets/6730496/7732383/36098172-ff5a-11e4-8521-ed8158e8bb5b.png)

**Comment by jvehent** [comment]
Why are you using `-j`? Do you need the results in json format? If not, just remove that flag from the command line.

**Comment by RoldanLT** [comment]
My bad :D
Thanks for the assistance :)
