### ISSUE TITLE
cypher list mismatch between webserver and analyze ?

### ISSUE THREAD

**Issue by akhepcat** [jvehent/cipherscan#56]
Analyze is throwing up bad cert errors, and it doesn't seem like it should:

From the webserver:
grep Cipher ssl.conf
        #   SSL Cipher Suite:
        SSLCipherSuite "ECDHE-RSA-AES128-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA128:DHE-RSA-AES128-GCM-SHA384:DHE-RSA-AES128-GCM-SHA128:ECDHE-RSA-AES128-SHA384:ECDHE-RSA-AES128-SHA128:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:AES128-GCM-SHA384:AES128-GCM-SHA128:AES128-SHA128:AES128-SHA128:AES128-SHA:AES128-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4"
        SSLHonorCipherOrder on

Given that config, here's what analyze says:

./analyze.py -t www.denali.net   
www.denali.net:443 has bad ssl/tls

Things that are bad:
* remove cipher EDH-RSA-DES-CBC3-SHA

Changes needed to match the old level:
* remove cipher EDH-RSA-DES-CBC3-SHA
* consider enabling SSLv3
* use a certificate with sha1WithRSAEncryption signature
* use DHE of 1024bits and ECC of 256bits
* consider enabling OCSP Stapling

Changes needed to match the intermediate level:
* remove cipher ECDHE-RSA-DES-CBC3-SHA
* remove cipher EDH-RSA-DES-CBC3-SHA
* consider enabling OCSP Stapling

Changes needed to match the modern level:
* remove cipher AES128-SHA
* remove cipher DHE-RSA-CAMELLIA256-SHA
* remove cipher AES256-GCM-SHA384
* remove cipher AES256-SHA256
* remove cipher AES256-SHA
* remove cipher CAMELLIA256-SHA
* remove cipher ECDHE-RSA-DES-CBC3-SHA
* remove cipher EDH-RSA-DES-CBC3-SHA
* remove cipher DES-CBC3-SHA
* remove cipher DHE-RSA-CAMELLIA128-SHA
* remove cipher AES128-GCM-SHA256
* remove cipher AES128-SHA256
* remove cipher CAMELLIA128-SHA
* disable TLSv1
* consider enabling OCSP Stapling

....  but there are no DES protocols enabled (or camellia, or...)

And here's what cipherscan details show:

./cipherscan -a --curves www.denali.net
..................................
Target: www.denali.net:443

prio  ciphersuite                  protocols              pfs                 curves
1     ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1
2     DHE-RSA-AES128-SHA           TLSv1,TLSv1.1,TLSv1.2  DH,4096bits         None
3     AES128-SHA                   TLSv1,TLSv1.1,TLSv1.2  None                None
4     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2                ECDH,P-256,256bits  prime256v1
5     ECDHE-RSA-AES256-SHA384      TLSv1.2                ECDH,P-256,256bits  prime256v1
6     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1
7     DHE-RSA-AES256-GCM-SHA384    TLSv1.2                DH,4096bits         None
8     DHE-RSA-AES256-SHA256        TLSv1.2                DH,4096bits         None
9     DHE-RSA-AES256-SHA           TLSv1,TLSv1.1,TLSv1.2  DH,4096bits         None
10    DHE-RSA-CAMELLIA256-SHA      TLSv1,TLSv1.1,TLSv1.2  DH,4096bits         None
11    AES256-GCM-SHA384            TLSv1.2                None                None
12    AES256-SHA256                TLSv1.2                None                None
13    AES256-SHA                   TLSv1,TLSv1.1,TLSv1.2  None                None
14    CAMELLIA256-SHA              TLSv1,TLSv1.1,TLSv1.2  None                None
15    ECDHE-RSA-DES-CBC3-SHA       TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1
16    EDH-RSA-DES-CBC3-SHA         TLSv1,TLSv1.1,TLSv1.2  DH,4096bits         None
17    DES-CBC3-SHA                 TLSv1,TLSv1.1,TLSv1.2  None                None
18    ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,P-256,256bits  prime256v1
19    ECDHE-RSA-AES128-SHA256      TLSv1.2                ECDH,P-256,256bits  prime256v1
20    DHE-RSA-AES128-GCM-SHA256    TLSv1.2                DH,4096bits         None
21    DHE-RSA-AES128-SHA256        TLSv1.2                DH,4096bits         None
22    DHE-RSA-CAMELLIA128-SHA      TLSv1,TLSv1.1,TLSv1.2  DH,4096bits         None
23    AES128-GCM-SHA256            TLSv1.2                None                None
24    AES128-SHA256                TLSv1.2                None                None
25    CAMELLIA128-SHA              TLSv1,TLSv1.1,TLSv1.2  None                None

Certificate: trusted, 4096 bit, sha512WithRSAEncryption signature
TLS ticket lifetime hint: None
OCSP stapling: not supported
Cipher ordering: server
Curves ordering: server
Curves fallback: False

All accepted ciphersuites
ADH-AES128-GCM-SHA256               fail
ADH-AES128-SHA                      fail
ADH-AES128-SHA256                   fail
ADH-AES256-GCM-SHA384               fail
ADH-AES256-SHA                      fail
ADH-AES256-SHA256                   fail
ADH-CAMELLIA128-SHA                 fail
ADH-CAMELLIA128-SHA256              fail
ADH-CAMELLIA256-SHA                 fail
ADH-CAMELLIA256-SHA256              fail
ADH-DES-CBC-SHA                     fail
ADH-DES-CBC3-SHA                    fail
ADH-RC4-MD5                         fail
ADH-SEED-SHA                        fail
AECDH-AES128-SHA                    fail
AECDH-AES256-SHA                    fail
AECDH-DES-CBC3-SHA                  fail
AECDH-NULL-SHA                      fail
AECDH-RC4-SHA                       fail
AES128-GCM-SHA256                   pass
AES128-SHA                          pass
AES128-SHA256                       pass
AES256-GCM-SHA384                   pass
AES256-SHA                          pass
AES256-SHA256                       pass
CAMELLIA128-SHA                     pass
CAMELLIA128-SHA256                  fail
CAMELLIA256-SHA                     pass
CAMELLIA256-SHA256                  fail
DES-CBC-MD5                         fail
DES-CBC-SHA                         fail
DES-CBC3-MD5                        fail
DES-CBC3-SHA                        pass
DH-DSS-AES128-GCM-SHA256            fail
DH-DSS-AES128-SHA                   fail
DH-DSS-AES128-SHA256                fail
DH-DSS-AES256-GCM-SHA384            fail
DH-DSS-AES256-SHA                   fail
DH-DSS-AES256-SHA256                fail
DH-DSS-CAMELLIA128-SHA              fail
DH-DSS-CAMELLIA128-SHA256           fail
DH-DSS-CAMELLIA256-SHA              fail
DH-DSS-CAMELLIA256-SHA256           fail
DH-DSS-DES-CBC-SHA                  fail
DH-DSS-DES-CBC3-SHA                 fail
DH-DSS-SEED-SHA                     fail
DH-RSA-AES128-GCM-SHA256            fail
DH-RSA-AES128-SHA                   fail
DH-RSA-AES128-SHA256                fail
DH-RSA-AES256-GCM-SHA384            fail
DH-RSA-AES256-SHA                   fail
DH-RSA-AES256-SHA256                fail
DH-RSA-CAMELLIA128-SHA              fail
DH-RSA-CAMELLIA128-SHA256           fail
DH-RSA-CAMELLIA256-SHA              fail
DH-RSA-CAMELLIA256-SHA256           fail
DH-RSA-DES-CBC-SHA                  fail
DH-RSA-DES-CBC3-SHA                 fail
DH-RSA-SEED-SHA                     fail
DHE-DSS-AES128-GCM-SHA256           fail
DHE-DSS-AES128-SHA                  fail
DHE-DSS-AES128-SHA256               fail
DHE-DSS-AES256-GCM-SHA384           fail
DHE-DSS-AES256-SHA                  fail
DHE-DSS-AES256-SHA256               fail
DHE-DSS-CAMELLIA128-SHA             fail
DHE-DSS-CAMELLIA128-SHA256          fail
DHE-DSS-CAMELLIA256-SHA             fail
DHE-DSS-CAMELLIA256-SHA256          fail
DHE-DSS-RC4-SHA                     fail
DHE-DSS-SEED-SHA                    fail
DHE-RSA-AES128-GCM-SHA256           pass
DHE-RSA-AES128-SHA                  pass
DHE-RSA-AES128-SHA256               pass
DHE-RSA-AES256-GCM-SHA384           pass
DHE-RSA-AES256-SHA                  pass
DHE-RSA-AES256-SHA256               pass
DHE-RSA-CAMELLIA128-SHA             pass
DHE-RSA-CAMELLIA128-SHA256          fail
DHE-RSA-CAMELLIA256-SHA             pass
DHE-RSA-CAMELLIA256-SHA256          fail
DHE-RSA-CHACHA20-POLY1305           fail
DHE-RSA-SEED-SHA                    fail
ECDH-ECDSA-AES128-GCM-SHA256        fail
ECDH-ECDSA-AES128-SHA               fail
ECDH-ECDSA-AES128-SHA256            fail
ECDH-ECDSA-AES256-GCM-SHA384        fail
ECDH-ECDSA-AES256-SHA               fail
ECDH-ECDSA-AES256-SHA384            fail
ECDH-ECDSA-CAMELLIA128-SHA256       fail
ECDH-ECDSA-CAMELLIA256-SHA384       fail
ECDH-ECDSA-DES-CBC3-SHA             fail
ECDH-ECDSA-NULL-SHA                 fail
ECDH-ECDSA-RC4-SHA                  fail
ECDH-RSA-AES128-GCM-SHA256          fail
ECDH-RSA-AES128-SHA                 fail
ECDH-RSA-AES128-SHA256              fail
ECDH-RSA-AES256-GCM-SHA384          fail
ECDH-RSA-AES256-SHA                 fail
ECDH-RSA-AES256-SHA384              fail
ECDH-RSA-CAMELLIA128-SHA256         fail
ECDH-RSA-CAMELLIA256-SHA384         fail
ECDH-RSA-DES-CBC3-SHA               fail
ECDH-RSA-NULL-SHA                   fail
ECDH-RSA-RC4-SHA                    fail
ECDHE-ECDSA-AES128-GCM-SHA256       fail
ECDHE-ECDSA-AES128-SHA              fail
ECDHE-ECDSA-AES128-SHA256           fail
ECDHE-ECDSA-AES256-GCM-SHA384       fail
ECDHE-ECDSA-AES256-SHA              fail
ECDHE-ECDSA-AES256-SHA384           fail
ECDHE-ECDSA-CAMELLIA128-SHA256      fail
ECDHE-ECDSA-CAMELLIA256-SHA384      fail
ECDHE-ECDSA-CHACHA20-POLY1305       fail
ECDHE-ECDSA-DES-CBC3-SHA            fail
ECDHE-ECDSA-NULL-SHA                fail
ECDHE-ECDSA-RC4-SHA                 fail
.ECDHE-RSA-AES128-GCM-SHA256         pass
.ECDHE-RSA-AES128-SHA                pass
.ECDHE-RSA-AES128-SHA256             pass
.ECDHE-RSA-AES256-GCM-SHA384         pass
.ECDHE-RSA-AES256-SHA                pass
.ECDHE-RSA-AES256-SHA384             pass
ECDHE-RSA-CAMELLIA128-SHA256        fail
ECDHE-RSA-CAMELLIA256-SHA384        fail
ECDHE-RSA-CHACHA20-POLY1305         fail
.ECDHE-RSA-DES-CBC3-SHA              pass
ECDHE-RSA-NULL-SHA                  fail
ECDHE-RSA-RC4-SHA                   fail
EDH-DSS-DES-CBC-SHA                 fail
EDH-DSS-DES-CBC3-SHA                fail
EDH-RSA-DES-CBC-SHA                 fail
EDH-RSA-DES-CBC3-SHA                pass
EXP-ADH-DES-CBC-SHA                 fail
EXP-ADH-RC4-MD5                     fail
EXP-DES-CBC-SHA                     fail
EXP-DH-DSS-DES-CBC-SHA              fail
EXP-DH-RSA-DES-CBC-SHA              fail
EXP-EDH-DSS-DES-CBC-SHA             fail
EXP-EDH-RSA-DES-CBC-SHA             fail
EXP-RC2-CBC-MD5                     fail
EXP-RC4-MD5                         fail
EXP1024-DES-CBC-SHA                 fail
EXP1024-DHE-DSS-DES-CBC-SHA         fail
EXP1024-DHE-DSS-RC4-SHA             fail
EXP1024-RC4-SHA                     fail
IDEA-CBC-MD5                        fail
IDEA-CBC-SHA                        fail
NULL-MD5                            fail
NULL-SHA                            fail
NULL-SHA256                         fail
PSK-3DES-EDE-CBC-SHA                fail
PSK-AES128-CBC-SHA                  fail
PSK-AES256-CBC-SHA                  fail
PSK-RC4-SHA                         fail
RC2-CBC-MD5                         fail
RC4-64-MD5                          fail
RC4-MD5                             fail
RC4-SHA                             fail
RSA-PSK-3DES-EDE-CBC-SHA            fail
RSA-PSK-AES128-CBC-SHA              fail
RSA-PSK-AES256-CBC-SHA              fail
RSA-PSK-RC4-SHA                     fail
SEED-SHA                            fail
SRP-3DES-EDE-CBC-SHA                fail
SRP-AES-128-CBC-SHA                 fail
SRP-AES-256-CBC-SHA                 fail
SRP-DSS-3DES-EDE-CBC-SHA            fail
SRP-DSS-AES-128-CBC-SHA             fail
SRP-DSS-AES-256-CBC-SHA             fail
SRP-RSA-3DES-EDE-CBC-SHA            fail
SRP-RSA-AES-128-CBC-SHA             fail
SRP-RSA-AES-256-CBC-SHA             fail

**Comment by tomato42** [comment]
the settings you use are enabling ECDHE-RSA-DES-CBC3-SHA and EDH-RSA-DES-CBC3-SHA, those ciphers are detected by `cipherscan`

I don't see the mismatch...

the "HIGH" string in your settings is enabling those, as well as CAMELLIA and the regular 3DES

see https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by akhepcat** [comment]
Ah!  I was grabbing the config from "https://cipherli.st/"   so I'll have to make sure to notate that.

Thanks.
