### ISSUE TITLE
UNTRUSTED google.com ?

### ISSUE THREAD

**Issue by centminmod** [jvehent/cipherscan#63]
I just downloaded latest cipherscan for my CentOS 6.6 system and seems having problems.. any clues ?

    ./cipherscan -v google.com
    Using trust anchors from /etc/pki/tls/certs/ca-bundle.crt
    Loading 0 ciphersuites from 
    .Connecting to 'google.com:443' with ciphersuite 'ALL:COMPLEMENTOFALL:+aRSA'
    selected cipher is ''
    using protocol ''
    selected cipher is ''
    using protocol ''
    selected cipher is ''
    using protocol ''
    selected cipher is ''
    using protocol ''
    selected cipher is ''
    using protocol ''
    handshake failed, no ciphersuite was returned
    
    Target: google.com:443
    
    
    Certificate: UNTRUSTED,  bit,  signature
    TLS ticket lifetime hint: 
    OCSP stapling: not supported
    Cipher ordering: server

thanks

**Comment by tomato42** [comment]
```
Loading 0 ciphersuites from 
```
that would indicate that it can't execute the bundled openssl. Are you running it on a non 64 bit intel (x86_64) system by any chance?

try:
```
./cipherscan -o `which openssl` google.com
```

**Comment by centminmod** [comment]
yup it's a 128MB CentOS 6.6 32bit OpenVZ VPS

this works though

    ./cipherscan -o `which openssl` google.com

**Comment by tomato42** [comment]
please close this bug report if it solves your issue

**Comment by centminmod** [comment]
cheers closed
