### ISSUE TITLE
analyze.py fails with the attached cipherscan output

### ISSUE THREAD

**Issue by kentfritz** [jvehent/cipherscan#64]
I get the following error:
Error processing data: can only concatenate list (not "str") to list

JSON output from cipherscan follows:
{"target":"kfritz-990.shoretel.com:9392","utctimestamp":"2015-07-06T21:23:36.0Z","serverside":"False","ciphersuite": [{"cipher":"ECDHE-RSA-AES256-GCM-SHA384","protocols":["TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"ECDH,P-521,521bits","curves":["secp521r1"]},{"cipher":"ECDHE-RSA-AES256-SHA","protocols":["TLSv1","TLSv1.1","TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"ECDH,P-521,521bits","curves":["secp521r1"]},{"cipher":"AES256-SHA256","protocols":["TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"None"},{"cipher":"AES256-SHA","protocols":["TLSv1","TLSv1.1","TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"None"},{"cipher":"CAMELLIA256-SHA","protocols":["TLSv1","TLSv1.1","TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"None"},{"cipher":"ECDHE-RSA-AES128-GCM-SHA256","protocols":["TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"ECDH,P-521,521bits","curves":["secp521r1"]},{"cipher":"ECDHE-RSA-AES128-SHA256","protocols":["TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"ECDH,P-521,521bits","curves":["secp521r1"]},{"cipher":"ECDHE-RSA-AES128-SHA","protocols":["TLSv1","TLSv1.1","TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"ECDH,P-521,521bits","curves":["secp521r1"]},{"cipher":"AES128-GCM-SHA256","protocols":["TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"None"},{"cipher":"AES128-SHA256","protocols":["TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"None"},{"cipher":"AES128-SHA","protocols":["TLSv1","TLSv1.1","TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"None"},{"cipher":"CAMELLIA128-SHA","protocols":["TLSv1","TLSv1.1","TLSv1.2"],"pubkey":["1024"],"sigalg":["sha1WithRSAEncryption"],"trusted":"False","ticket_hint":"None","ocsp_stapling":"False","pfs":"None"}]}

**Comment by tomato42** [comment]
c9529b5 got merged so it now works for me both with python2 and python3, I think it can be closed as resolved
