### ISSUE TITLE
Dependency on bash

### ISSUE THREAD

**Issue by zg** [jvehent/cipherscan#66]
```
$ cipherscan zk.gd
Bash version 4 is required to run cipherscan.
Please upgrade your version of bash (ex: brew install bash).
$ echo $SHELL      
/usr/local/bin/zsh
```
:-1:

**Comment by jvehent** [comment]
Unless you would you like to contribute a rewrite of cipherscan to be compatible with zsh, I don't see how to make progress on this issue. Bash is standard to most (all?) *nix systems, so it's the logical common denominator for scripting.

**Comment by tomato42** [comment]
we are also using a lot of bash specific features

it's more of a real program written in bash syntax than "just" a shell script - I'm afraid that to make it POSIX compatible would require it to be at least twice as big 

also, when I have time, I prefer to work on a python version - exactly to make the code simpler and easier to read, not larger and more complex

**Comment by zg** [comment]
:+1:

I'll watch and wait. :-)

**Comment by jungle-boogie** [comment]
I'd be happier if this was written in /bin/sh but I'll watch and wait for a python version.

**Comment by PeterMosmans** [comment]
Instead of watching and waiting - feel more than welcome to actively participate and contribute. It's open source after all, the more the merrier :smile:
