### ISSUE TITLE
Cipher suite analyse problem

### ISSUE THREAD

**Issue by hardware** [jvehent/cipherscan#71]
Why is it considered bad practice to use **ECDHE-RSA-AES128-GCM-SHA256** cipher ? I do not understand why ?

![screen](https://i.gyazo.com/14157da9f4968b61dd89b0a69a5f6af9.png)

This cipher is considered safe and secure today.

**Comment by jvehent** [comment]
That looks like a bug.

**Comment by tomato42** [comment]
yes, it's continuation of Python 3 issues - there are few other places where `subprocess` output is used, #70 should fix this

**Comment by hardware** [comment]
This fix work, thank again @tomato42 :smile:
