### ISSUE TITLE
Use SNI by default

### ISSUE THREAD

**Issue by jvehent** [jvehent/cipherscan#88]
I caught myself twice today because I  forgot to give `-servername` to cipherscan while scanning a site. I think it should become the default, as tons of sites depend on it nowadays. Any reason not to make it the default?

**Comment by tomato42** [comment]
in top1m scan we do the DNS resolving outside cipherscan script, so the `-connect` in s_client gets just the IP address

there are also situations when you want to scan a local host that may not have a DNS record set, and using IP address as a parameter to -servername violates the RFC - you can put hostnames only there

so, as long as the code detects if the hostname passed in is not an IP address, and that user didn't specify the -servername manually, I don't see a problem with that

**Comment by jvehent** [comment]
I started some basic support in #90
You can turn off automatic SNI by providing `--no-sni` to the command line.
It doesn't detect that the target is an IP address, or that the issuer has provided a `servername` parameter. I'll add that.

**Comment by jvehent** [comment]
implemented
