### ISSUE TITLE
./cipherscan | whatever includes ANSI color codes

### ISSUE THREAD

**Issue by floatingatoll** [jvehent/cipherscan#94]
When trying to use cipherscan latest, I got observed color codes being output to non-terminal outputs.

**Comment by jvehent** [comment]
Can you be more specific? The color coding is only used in `display_results_in_terminal` so I'm not sure how a non-terminal output could trigger it.

**Comment by floatingatoll** [comment]
./cipherscan | pbcopy 

Put ansi on the clipboard for me. Calling the non-JSON output "terminal" doesn't guarantee that the desired output IS a terminal. Consider [[ -t ]] or similar methods to detect whether STDOUT is a tty.

**Comment by tomato42** [comment]
this does come close to the "it hurts? then don't do it"...

terminal output is not meant to be machine readable

**Comment by floatingatoll** [comment]
It is inappropriate to presume to invoke "machine readable" here, as you are not familiar with my workflow.

Unnecessarily including ANSI codes to non-TTY outputs is bad form.

See also behavior of e.g. ls and git, which disable color when piped to a non-TTY.

pbcopy is the OS X command line tool for piping a command into the clipboard for pasting into, say, an email to a vendor.

**Comment by tomato42** [comment]
then use `--no-colors` switch

and while that may be your workflow, in my workflow I often force both grep and ls to use colour when piped to `less` as I want to easily search through their output and still have interesting stuff highlighted with colour

**Comment by floatingatoll** [comment]
This is counter to expectations set by other UNIX programs. In those instances when I am using less -R, I expect based on common experience to have to force colors on. Having to disable colors on non-TTY outputs by hand is uncommon and frustrating.

**Comment by jvehent** [comment]
@floatingatoll : Any thought on how to detect that stdout is not a terminal? I think that would be a neat addition.

**Comment by drwetter** [comment]
tty -s

**Comment by tomato42** [comment]
@drwetter doesn't work:
```
$ tty | cat 
/dev/pts/6
```

**Comment by tomato42** [comment]
the `[[ -t 1 ]]` will return true if the _stdout_ is on tty

I'll make one that does that automatically and allows override

**Comment by drwetter** [comment]
@tomato42 of course it does, you need to add the ``-s`` :-)

**Comment by tomato42** [comment]
`tty` command checks _stdin_, option to turn it silent won't change it...

or to put it otherwise, it checks for this:
```
$ tty </dev/null
not a tty
$ echo $?
1
```

:innocent:

**Comment by floatingatoll** [comment]
See also:

http://unix.stackexchange.com/a/10065

And

http://mywiki.wooledge.org/BashFAQ/037

For more extensive discussions on the topic, if interested.
